---
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.ernesttech.samdemo.HelloWorldHandler
      Runtime: java8
      CodeUri: ./target/aws-sam-local-vagrant-demo-0.0.1-SNAPSHOT.jar
